### ISSUE TITLE
Zero-indexed frame on stop()

### ISSUE THREAD

**Issue by dominicwa** [antonjb/Sprite#2]
This doesn't work...

<pre>this.rocketSprite.stop(
    0,
    true,
    function() {
        console.log("I didn't make it here :(");
    }
)</pre>

This does...

<pre>this.rocketSprite.stop(
    1,
    true,
    function() {
        console.log("Made it!");
    }
)</pre>

**Comment by antonjb** [comment]
Big sorted in version 1.0.1
